Repository oz-main-10-team1/yours-scently-be, pull requests merged in 2025-07, with the labels that each got.

#3 feature/SCENTLY-12--add-user-model
  apps/__init__.py
  apps/users/manager/__init__.py
  apps/users/manager/user_manager.py
  apps/users/migrations/0001_initial.py
  apps/users/migrations/0002_user_role_alter_user_password.py
  apps/users/models.py
  apps/users/models/__init__.py
  apps/users/models/user.py
  config/settings/base.py
Labels: feature

#6 📝 docs: 커밋 템플릿 및 PR 템플릿 변경 (SCENTLY-18)
  .github/commit_template.txt
  .github/pull_request_template.md
  resources/nginx/Dockerfile
Labels: docs

#8 📝 docs: 스웨거 문서 추가 (SCENTLY-16)
  config/settings/base.py
  config/urls.py
  poetry.lock
  pyproject.toml
Labels: docs

#18 ✨ feat: products model 작성 (SCENTLY-32)
  apps/product/__init__.py
  apps/product/admin.py
  apps/product/apps.py
  apps/product/migrations/0001_initial.py
  apps/product/migrations/__init__.py
  apps/product/models.py
  apps/product/models/__init__.py
  apps/product/models/product.py
  apps/product/tests.py
  apps/product/views.py
  config/settings/base.py
Labels: feat

#23 ✨ feat: 향수 추천 모델 작성(SCENTLY-41)
  apps/product/migrations/0002_alter_product_product_img_url_perfume.py
  apps/product/models/perfume.py
  apps/recommendation/__init__.py
  apps/recommendation/migrations/0001_initial.py
  apps/recommendation/migrations/__init__.py
  apps/recommendation/models/__init__.py
  apps/recommendation/models/recommendation.py
  apps/users/migrations/0009_delete_perfume.py
  config/settings/base.py
Labels: feat

#27 ✨ feat: like 모델 작성 (SCENTLY-51)
  apps/product/migrations/0005_like.py
  apps/product/models.py
  apps/product/models/__init__.py
  apps/product/models/like.py
  apps/product/tests.py
  apps/product/tests/__init__.py
  apps/product/views.py
  apps/product/views/__init__.py
Labels: feat

#28 💡 chore: 파일구조 변경 (SCENTLY-50)
  apps/product/migrations/0001_initial.py
  apps/product/migrations/0002_alter_product_product_img_url.py
  apps/product/migrations/0002_alter_product_product_img_url_perfume.py
  apps/product/migrations/0002_initial.py
  apps/product/migrations/0003_merge_20250730_1725.py
  apps/product/migrations/0004_usagehistory.py
  apps/product/migrations/0005_like.py
  apps/product/models/__init__.py
  apps/product/models/accord.py
  apps/product/models/note.py
  apps/product/models/perfume.py
  apps/recommendation/migrations/0001_initial.py
  apps/users/migrations/0001_initial.py
  apps/users/migrations/0002_user_role_alter_user_password.py
  apps/users/migrations/0003_socialuser.py
  apps/users/migrations/0003_user_gender.py
  apps/users/migrations/0004_merge_0003_socialuser_0003_user_gender.py
  apps/users/migrations/0005_accord_note_perfume.py
  apps/users/migrations/0006_alter_user_is_active.py
  apps/users/migrations/0006_fragrancepreference.py
  apps/users/migrations/0007_merge_20250729_1638.py
  apps/users/migrations/0008_withdrawal.py
  apps/users/migrations/0009_delete_perfume.py
  apps/users/migrations/0010_searchlog.py
  apps/users/models/__init__.py
  apps/users/models/fragrance_preference.py
Labels: chore

#30 ✨ feat: 좋아요 API 작성 (SCENTLY-52)
  apps/product/migrations/0003_alter_usagehistory_user_like.py
  apps/product/models/__init__.py
  apps/product/serializers/__init__.py
  apps/product/serializers/like_serializer.py
  apps/product/tests/test_product_like.py
  apps/product/urls.py
  apps/product/views/like_views.py
  config/urls.py
Labels: feat

#31 ✨ feat: 카트 모델 작성 (SCENTLY-54)
  apps/commerce/__init__.py
  apps/commerce/admin.py
  apps/commerce/apps.py
  apps/commerce/migrations/0001_initial.py
  apps/commerce/migrations/__init__.py
  apps/commerce/models/__init__.py
  apps/commerce/models/cart.py
  apps/commerce/tests.py
  apps/commerce/views.py
  apps/product/migrations/0003_alter_usagehistory_user.py
  apps/product/migrations/0004_merge_20250731_1537.py
  config/settings/base.py
Labels: feat

#32 ✨ feat: 좋아요 목록 조회 API 작성 (SCENTLY-56)
  apps/product/serializers/like_list_serializer.py
  apps/product/tests/test_like_list.py
  apps/product/urls.py
  apps/product/views/like_list_view.py
  apps/recommendation/models/recommendation_history.py
Labels: feat
