Repository oz-main-10-team1/yours-scently-be, pull requests merged in 2025-08, with the labels that each got.

#38 ✨ feat: 이메일 찾기 API 작성(SCENTLY-62)
  apps/users/serializers/auth/find_email_phone_verification.py
  apps/users/serializers/find_account_serializers.py
  apps/users/tests/test_account_find.py
  apps/users/urls.py
  apps/users/utils/email_masking_utils.py
  apps/users/utils/redis_utils.py
  apps/users/views/auth/find_email_phone_verification.py
  apps/users/views/find_account_views.py
Labels: feat

#42 ✨ feat: 내 정보 수정 API 작성 (SCENTlY-67)
  apps/users/serializers/my_profile.py
  apps/users/tests/test_myprofile_update.py
  apps/users/urls.py
  apps/users/views/my_profile.py
Labels: feat

#45 🚚 build: 도메인 적용 (SCENTLY-72)
  config/settings/dev.py
  resources/nginx/prod.conf
Labels: build

#46 refactor: 디버그문 삭제 (SCENTLY-81)
  config/urls.py
Labels: refactor

#43 ✨ feat: 사용자 취향 삭제 API 추가(SCENTLY-65)
  apps/users/tests/test_fragrance_preference_delete.py
  apps/users/urls.py
  apps/users/views/fragrance/fragrance_preference_delete.py
Labels: feat

#48 ✨ feat: 비밀번호 변경 API 작성 (SCENTLY-83)
  apps/product/migrations/0007_remove_perfume_concentration_alter_perfume_intensity.py
  apps/product/migrations/0008_product_perfume.py
  apps/product/models/perfume.py
  apps/product/models/product.py
  apps/users/serializers/my_profile.py
  apps/users/tests/test_myprofile_change_password.py
  apps/users/urls.py
  apps/users/views/my_profile.py
Labels: feat

#40 feat:상품목록조회API 작성(SCENTLY-26)
  apps/product/migrations/0009_product_views_count.py
  apps/product/models/product.py
  apps/product/serializers/product_serializers.py
  apps/product/tests/test_product_list.py
  apps/product/urls.py
  apps/product/views/product_views.py
Labels: feat

#51 ✨ feat: 내 정보 수정 휴대폰 인증 API (SCENTLY-88)
  apps/users/serializers/my_profile.py
  apps/users/tests/test_myprofile_change_phonenumber.py
  apps/users/urls.py
  apps/users/views/my_profile.py
Labels: feat

#52 💡 chore: 사용자 취향 API 파일 평합(SCENTLY-89)
  apps/users/serializers/fragrance/fragrance_preference.py
  apps/users/serializers/fragrance/fragrance_preference_update.py
  apps/users/tests/test_fragrance_preference.py
  apps/users/tests/test_fragrance_preference_delete.py
  apps/users/tests/test_fragrance_preference_update.py
  apps/users/urls.py
  apps/users/views/fragrance/fragrance_preference.py
  apps/users/views/fragrance/fragrance_preference_delete.py
  apps/users/views/fragrance/fragrance_preference_update.py
Labels: chore

#53 Fix/scently 95—fix signup api
  apps/users/serializers/auth/find_email_phone_verification.py
  apps/users/serializers/auth/phone_auth.py
  apps/users/serializers/auth/signup.py
  apps/users/tasks.py
  apps/users/tests/test_account_find.py
  apps/users/tests/test_auth_signup.py
  apps/users/urls.py
  apps/users/utils/redis_utils.py
  apps/users/utils/twilio_utils.py
  apps/users/views/auth/find_email_phone_verification.py
  apps/users/views/auth/phone_auth.py
  apps/users/views/find_account_views.py
  config/settings/base.py
Labels: fix

#55 ✨ feat: 향수 리뷰 저장 API 추가(SCNETLY-91)
  apps/review/migrations/0001_initial.py
  apps/review/serializers/__init__.py
  apps/review/serializers/review.py
  apps/review/tests/__init__.py
  apps/review/tests/test_review.py
  apps/review/urls.py
  apps/review/views/__init__.py
  apps/review/views/review.py
  config/settings/base.py
  config/urls.py
Labels: feat

#56 ✨feat: 마이페이지 조회 API 작성 (SCENTLY-97)
  apps/product/migrations/0010_mainaccord_perfume_users_alter_perfume_main_accords.py
  apps/product/migrations/0011_merge_20250808_1648.py
  apps/product/models/__init__.py
  apps/product/models/accord.py
  apps/product/models/perfume.py
  apps/users/serializers/my_page.py
  apps/users/serializers/my_profile.py
  apps/users/tests/test_mypage.py
  apps/users/tests/test_myprofile_change_phonenumber.py
  apps/users/urls.py
  apps/users/views/my_page.py
  apps/users/views/my_profile.py
Labels: feat

#59 feat: AI 추천 API 작성 (SCENTLY-60)
  apps/recommendation/migrations/0002_recommendation_reason.py
  apps/recommendation/models/recommendation.py
  apps/recommendation/serializers/ai_recommendation_serializer.py
  apps/recommendation/tests/test_ai_recommendation.py
  apps/recommendation/urls.py
  apps/recommendation/utils/ai_recommendation.py
  apps/recommendation/views/ai_recommendation_view.py
  config/settings/base.py
Labels: feat

#54 Feat: 상품 상세 목록 API작성(SCENTLY-82)
  .gitignore
  apps/product/serializers/products_detail_serializers.py
  apps/product/tests/test_product_detail.py
  apps/product/tests/test_product_list.py
  apps/product/urls.py
  apps/product/views/products_detail_views.py
Labels: feat

#61 feat: ai 추천 이력 조회 API 작성 (SCENTLY-61)
  apps/recommendation/migrations/0003_recommendation_description.py
  apps/recommendation/models/recommendation.py
  apps/recommendation/serializers/ai_recommendation_serializer.py
  apps/recommendation/tests/test_ai_recommendation.py
  apps/recommendation/urls.py
  apps/recommendation/views/ai_recommendation_view.py
  poetry.lock
  pyproject.toml
Labels: feat

#62 feat: 마이페이지 수정 API 작성
  apps/users/serializers/my_page.py
  apps/users/tests/test_mypage_update.py
  apps/users/urls.py
  apps/users/views/my_page.py
  docker-compose.yml
Labels: feat

#66 fix: ci runtime 시간 변경 (SCENTLY-113)
  .github/workflows/dev-deploy.yml
Labels: fix

#68 fix: cd runtime 변경 (SCENTLY-115)
  .github/workflows/dev-deploy.yml
Labels: fix

#69 fix: 도커 컴포즈 셀러리 수정 (SCENTLY-116)
  Dockerfile.celery
  docker-compose.yml
Labels: fix

#71 fix: 도커파일 수정(SCENTLY-117)
  .dockerignore
  Dockerfile
Labels: fix

#70 feat: 설문조사 향수 추천 사유 제공 API 작성 (SCENTLY-110)
  apps/recommendation/serializers/survey_recommendation_reason_serializer.py
  apps/recommendation/tests/test_survey_recommendation_reason.py
  apps/recommendation/urls.py
  apps/recommendation/views/survey_recommendation_reason_view.py
Labels: feat

#73 feat: 향수 리뷰 조회 API (SCENTLY-118)
  apps/review/pagination.py
  apps/review/serializers/review_list_serializer.py
  apps/review/tests/test_review_list.py
  apps/review/urls.py
  apps/review/views/review_list_view.py
Labels: feat

#74 feat: s3 업로더 추가 (SCENTLY-109)
  .dockerignore
  Dockerfile
  config/settings/base.py
  core/utils/s3_uploader.py
  poetry.lock
  pyproject.toml
Labels: feat

#75 💡 chore: 스웨거 업데이트
  apps/review/views/review.py
  apps/review/views/review_summary.py
  apps/review/views/user_review.py
  apps/users/views/fragrance/fragrance_preference.py
Labels: chore

#78 fix: 도커파일 수정 (SCENTLY-125)
  Dockerfile
Labels: fix
